# Generated by Django 5.2.6 on 2026-03-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_free_service_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('TECHNICIAN', 'Technician'), ('AMC', 'AMC'), ('AFFILIATE', 'Affiliate')], default='CUSTOMER', max_length=50),
        ),
    ]
