# Generated by Django 5.2.6 on 2026-03-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_affiliate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['is_amazon_affiliate', '-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_affiliate_link',
            field=models.URLField(blank=True, help_text='Amazon Affiliate Link', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_amazon_affiliate',
            field=models.BooleanField(default=False, help_text='Is this an Amazon affiliate product?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique, URL-friendly name for the product.', max_length=255, null=True, unique=True),
        ),
    ]
