# Generated by Django 5.2.6 on 2026-03-29 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_options_product_amazon_affiliate_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Banner image (recommended 1400×400)', upload_to='banners/')),
                ('button_text', models.CharField(blank=True, help_text="CTA button label, e.g. 'Shop Now'. Leave blank for no button.", max_length=50)),
                ('external_link', models.URLField(blank=True, help_text='External URL if no product is linked (optional)', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this banner on the store')),
                ('product', models.ForeignKey(blank=True, help_text='Link button to this product page (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
            options={
                'verbose_name': 'Store Banner',
                'verbose_name_plural': 'Store Banners',
                'ordering': ['order'],
            },
        ),
    ]
