# Generated by Django 5.2.6 on 2026-04-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_delivered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
