# Generated by Django 5.2.6 on 2026-03-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_jobsheet_jobsheetmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Technician Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20),
        ),
    ]
