# Generated by Django 5.2.6 on 2026-03-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_request_price', models.DecimalField(decimal_places=2, default=500.0, help_text='Default price to charge for custom service requests where no specific issue is selected.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Service Setting',
                'verbose_name_plural': 'Service Settings',
            },
        ),
    ]
