# Generated by Django 5.2.6 on 2026-03-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='custom_request_price',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Default price to charge for custom service requests in this category.', max_digits=10),
        ),
    ]
